import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Slider from '../components/Slider'

export default function Home() {
 
  return (

    <div>

    <Head>
      <title> Prefab Davao</title>
      <meta name='Description' content='Generated by SAD Researchers' />
      <link rel='icon' href='https://www.facebook.com/PrefabDavao' />
    </Head>
    <Hero heading='Prefab Davao' message='SAMPLE' />
    <Slider slides={SliderData}/>
    </div>
  )
}